### ISSUE TITLE
Ensure new categories are in the database - they aren't showing up in the console at the moment

### ISSUE THREAD

**Issue by trigger2896** [shnergle/ShnergleServer#41]

**Comment by krzd** [comment]
We are not saving the categories in the database anymore, as it had only negative aspects.
The reason why some categories (the new ones, but also for instance 'Bus') do not show up, is because there are no venues for those categories.
So, we look into the database which category_id's exist in the table venues, and then translate it to a name, because categories without venues have no entry there, they do not appear in the graph.
VenueCategories under Venues only exists for legacy reasons, as it is used by v1.0 through v1.2, and should not be changed as it can cause issues in those versions. Newer versions do not use that table at all.

**Comment by trigger2896** [comment]
ok - happy with that. :-)
